# Status bar

exec-once = systemctl --user start --now hyprpaper.service


# start ssh-agent on login
exec-once = ~/.config/hypr/scripts/start-ssh-agent.sh

exec-once = nm-applet

exec-once = waypaper --restore


# En tu hyprland.conf
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Otis'
