hl.on("hyprland.start", function()
	hl.exec_cmd("waybar & waypaper --restore")
	hl.exec_cmd("gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'")
	hl.exec_cmd("gsettings set org.gnome.desktop.interface color-scheme 'Otis'")
end)
